version: '3'

services:
  cstask:
    image: cs_task:latest
    container_name: cstask
    ports:
      - "8080:8080"
    build:
      context: .
    networks:
      - back-tier
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus_config.yaml'
    networks:
      - back-tier
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config/grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

networks:
  front-tier:
  back-tier: